### ISSUE TITLE
No results on Ubtuntu 16.04

### ISSUE THREAD

**Issue by jgbneatdesign** [teamtnt/tntsearch#23]
Hello! As I mentioned in one of my email lately, I'm very happy to use the package for the performance it gives my app and such but I've been having a couple of issues with it. I started implementing a search feature in Laravel app on a Mac. It worked fine, even with a few bugs, but it worked. I then switched to using a PC with Ubuntu 16.04 and since then the package stopped working. At first it said "PHP driver not found". I then installed php7.0-sqlite3. I have sqlite3 installed on the machine so trying to open the index files created from artisan works fine. I can do a "select * from wordlist" for example and I got some results. But it doesn't show anything in the application. I got empty results whenever I try.

What am I doing wrong?

- Regards for your awesome work

**Comment by nticaric** [comment]
Have you run the indexer again or did you just move the index files over?
What are the file permissions of your storage folder?

**Comment by jgbneatdesign** [comment]
The storage permission is drwxrwxr-x 
The database file permission is -rw-r--r--.

**Comment by jgbneatdesign** [comment]
And yes I re-run the indexer From a fresh Laravel install just so I could be sure.

**Comment by nticaric** [comment]
It's hard to say what could be wrong here. I think your only option is to trace the function calls to see
where it went wrong. Try with a word that you are sure is in the index, and keep in mind that the index contains stemmed words not the real ones. So if you for example search for the word `yes` you'll find it in the wordlist as `ye`

**Comment by jgbneatdesign** [comment]
I don't think that's the problem. Maybe it has to do with the sqlite driver
or something. Will try to reinstall it and see what happens.

**Comment by nticaric** [comment]
Have you managed to solve your issue?

**Comment by mphill** [comment]
1) TNTSearchTest::testSearchBoolean
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    0 => 7
 )


On PHP 7.0.8 with sqlite3 - No result id in ids array

**Comment by mphill** [comment]
I tracked this down to

`public function getWordlistByKeyword($keyword, $isLastWord = false)`

What is VERY bizarre is loading sqlite3 <index> Running this: 

> SELECT * FROM wordlist WHERE term LIKE 'phone'; <-- Fail

> SELECT * FROM wordlist WHERE cast(term as text) LIKE 'phone'; <-- I get results

Tweaking the code in this method to the following makes the indexer work. I am inclined to believe there is some bug in the client library.  Or there is something really weird happening with column affinity. https://www.sqlite.org/datatype3.html

```
        $searchWordlist = "SELECT * FROM wordlist WHERE cast(term as text) like :keyword LIMIT 1";
        $stmtWord       = $this->index->prepare($searchWordlist);

        if ($this->asYouType && $isLastWord) {
            $searchWordlist = "SELECT * FROM wordlist WHERE cast(term as text) like :keyword ORDER BY length(term) ASC, num_hits DESC LIMIT 1";
            $stmtWord       = $this->index->prepare($searchWordlist);
            $stmtWord->bindValue(':keyword', mb_strtolower($keyword) . "%");
        } else {
            $stmtWord->bindValue(':keyword', mb_strtolower($keyword));
        }
```

**Comment by nticaric** [comment]
@mphill good catch. I also think there is something wrong with the sqlite3 verison 3.11.0. 
The column datatype is recognized as `BLOB` instead of `TEXT`. I asked a question on stackoverflow to see whats going on

http://stackoverflow.com/questions/38489509/sqlite3-where-clause-doesnt-return-anything-if-datatype-is-blob

**Comment by nticaric** [comment]
Hopefully this ubuntu 16.04 bug is now fixed with the v0.7.1 release. Can you guys test and confirm?

**Comment by mphill** [comment]
That did not appear to fix it.  Let me dig into your commit change log

**Comment by nticaric** [comment]
@mphill does phpunit still fail for you?

**Comment by mphill** [comment]
Its working.

**You have to regenerate existing the indexes.** 

All unit tests passed.

**Comment by nticaric** [comment]
Great! Yeah, the existing index files need to be regenerated
